<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
 * hoteles_helper
 *
 */	


/*
 * getRRCount
 *
 * Returns how many rooms are in a reservation 
 *
 * @access	public
 * @return	string
 */	

function getPaymentInfo($hotel, $field, $value, $reservationId)
{
	$CI =& get_instance();

	$CI->load->model('reservations_model');
	
	$result = $CI->reservations_model->getPaymentInfo($hotel, $field, $value, $reservationId);
		
	return $result;
}

/*
function getPaymentsAmount($hotel, $reservationId)
{
	$CI =& get_instance();

	$CI->load->model('reservations_model');
	
	$result = $CI->reservations_model->getPaymentsAmount($hotel, $reservationId);
		
	return $result;
}
*/


function getRRCount($hotel, $field1, $value1, $field2, $value2)
{
	$CI =& get_instance();

	$CI->load->model('rooms_model');
	
	$result = $CI->rooms_model->getRRCount($hotel, $field1, $value1, $field2, $value2);
		
	return $result;
}


function getRRInfo($hotel, $field, $value)
{
	$CI =& get_instance();

	$CI->load->model('rooms_model');
	
	$result = $CI->rooms_model->getRRInfo($hotel, $field, $value);
		
	return $result;
}


function getInfo($hotel, $table, $field, $value, $order, $lim1, $lim2, $disable)
{
	$CI =& get_instance();

	$CI->load->model('general_model');
	
	$result = $CI->general_model->getInfo($hotel, $table, $field, $value, $order, $lim1, $lim2, $disable);
		
	return $result;
}


function getNick($string)
{
	$string = htmlentities(strtolower(trim($string))); //Chages accented letters with html format &xacute; style
	$string = preg_replace('/\"/','',$string); //Removes Double Quotes - NOT WORKING
	$string = preg_replace("/\'/","",$string); // Removes Single Quotes
   	$string = preg_replace("/&([a-z])[a-z]+;/i","$1",$string); //removes everything after the & generated by htmlentities
	$string = preg_replace("/[^a-z0-9_]/",' ',$string); // Convert to whitespace chars different than letters ,numbers, and underscore
	$string = preg_replace('/\s+/', '_', $string); // Replaces multiple or single whitespaces with underscore
	
	return $string;
}
